### ISSUE TITLE
Tools suitable for mobile use

### ISSUE THREAD

**Issue by Ainali** [johnsamuelwrites/awesome-wikidata#2]
Would it make sense to add a note (or an icon) for the tools that are easy to use on a mobile phone?

**Comment by johnsamuelwrites** [comment]
@Ainali Thank you for this suggestion. I have updated the list. The following characters precise the availability of tools on different platforms.
* 🖥 available on PC desktop
* 📱 available on mobile phones

Please check https://github.com/johnsamuelwrites/awesome-wikidata/blob/main/README.md.

**Comment by johnsamuelwrites** [comment]
Closing this issue as the list has been updated and instructions for future contributors have been provided.
